# Generated by Django 3.2.6 on 2021-08-26 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20210824_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
