# Generated by Django 3.2.6 on 2021-09-16 20:58

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_field',
            field=models.CharField(choices=[('Сауна', 'сауна'), ('Чан', 'чан')], default='Сауна', max_length=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='user_phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=13, validators=[django.core.validators.RegexValidator(message='Phone in format xxx xxx xxxx', regex='(\\d{3}[- .]?){2}\\d{4}$')]),
            preserve_default=False,
        ),
    ]
