# Generated by Django 3.2.6 on 2021-09-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_calendar', '0002_auto_20210916_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_field',
            field=models.CharField(choices=[('сауна', 'Сауна'), ('чан', 'Чан')], default='Сауна', max_length=5),
        ),
    ]
