# Generated by Django 3.2.6 on 2021-09-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_calendar', '0004_alter_booking_service_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='data_field',
            new_name='date_field',
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_field',
            field=models.CharField(max_length=5),
        ),
    ]
